#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar  5 17:12:27 2020

@author: paulcalvi
"""

import numpy as np
import matplotlib.pyplot as plt
import sympy

Xo = np.linspace(-10,10,1000)
theta = np.linspace(0,2*np.pi,1000)
Xc = 2*np.cos(theta)
Yc = 2*np.sin(theta)
def Ray(Nb=5, L_Beam = 1, type_m = 'concave'):
    lst_sol = []
    Ray = []
    X_lst = []
    ray_lst= []
    for n in range(Nb):
        
        x, y = sympy.symbols('x,y')
        eq1 = x**2+y**2-2**2
        eq2 = 0*x-y+n*(L_Beam/Nb)
        sol = sympy.solve([eq1,eq2], [x,y])
        lst_sol.append(sol) #liste de solution [[(x1,y1),(x2,y2)],...,[(x, y),(x, y)]]
        
        X_grp = []
        
        if type_m == 'concave':
        
            for x in Xo:
                if x<lst_sol[n][1][0] :
                    ray = x*0+(L_Beam/Nb)*n
                if x>lst_sol[n][1][0]:
                    ray = x*0
                    
                X_grp.append(ray)
                
        if type_m == 'convexe':
            
            for x in Xo:
                if x<lst_sol[n][0][0] :
                    ray = x*0+(L_Beam/Nb)*n
                if x>lst_sol[n][0][0]:
                    ray = x*0
        
                
                X_grp.append(ray)
            
        Ray.append(X_grp)
        
        X = np.linspace(np.min(Xo),lst_sol[n][1][0], 1000 )
        ray = X*2*(lst_sol[n][0][1]/lst_sol[n][0][0])+lst_sol[n][0][0]
        
        X_lst.append(X)
        ray_lst.append(ray)
        
        Ray.append([X_grp,ray_lst])
        
    return Ray


beam = Ray(type_m  = 'convexe')
fig, ax = plt.subplots()
for i in range(5):
    ax.plot(Xo,beam[i])
ax.plot(Xc,Yc)
plt.show()