#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  4 14:48:56 2020

@author: paulcalvi
"""

import numpy as np
import sympy
import matplotlib.pyplot as plt 
  

 
fig, ax = plt.subplots()
ax.plot(Xc, Yc , color = 'black')
ax.plot(Xo,Yo, '--', color = 'gray')
ax.plot(0, 0, 'o', color = 'black', label = 'C')
ax.plot()
#ax.arrow([x, Yo, 13, 0, head_width=0.5, head_length=0.5, fc='k', ec='k') ajout flèche sur la droite 
ax.legend()
ax.plot()




"""
lst_sol = []
for i in range(5):
    x, y = sympy.symbols('x y')
    eq1 = x**2+y**2-5**2
    eq2 = 0*x-y+i
    sol = sympy.solve([eq1,eq2], [x,y])
    lst_sol.append(sol)

    print(lst_sol[i][1][0])

"""


"""
diam_ouv = 6
r = 4
angle_ouv = np.arcsin(frac(diam_ouv,2*r))
theta = np.linspace(-np.pi/2-angle_ouv, -np.pi/2+angle_ouv)
Yc = -r*np.cos(theta)
Xc = r*np.sin(theta)
""""""
fig, ax = plt.subplots()
ax.set_xlim(-10, 10)
ax.set_ylim(-10, 10)
""""""
ax.plot(Xc, Yc , color = 'black')
ax.plot(Xo,Yo, '--', color = 'gray')
ax.plot(0, 0, 'o', color = 'black', label = 'C')
ax.plot()
#ax.arrow([x, Yo, 13, 0, head_width=0.5, head_length=0.5, fc='k', ec='k') ajout flèche sur la droite 
ax.legend()
ax.plot()

"""