#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  8 16:30:46 2020

@author: paulcalvi
"""
import matplotlib.pyplot as plt
import numpy as np

H = 5
L = 2


theta = np.linspace(0,2*np.pi,1000)
Xc = L/2*np.cos(theta)
Yc = H/2*np.sin(theta)


fig, ax = plt.subplots()
ax.plot(Xc, Yc, color = 'blue', alpha = 0.2)
ax.fill_between(Xc, Yc  , facecolor='blue', alpha=0.1)

ax.set_xlim(-10,10)
plt.show()

